### ISSUE TITLE
Additional RL agents needed

### ISSUE THREAD

**Issue by janstenner** [upb-lea/ElectricGrid.jl#100]
We need to implement additional RL agents besides ddpg.

@VikasChidananda will try to implement SAC and TD3.

**Comment by VikasChidananda** [comment]
References for TD3:
1. [spinning up](https://spinningup.openai.com/en/latest/algorithms/td3.html)
    [code](https://github.com/openai/spinningup/tree/master/spinup/algos/pytorch/td3) 
2. [Julia TD3](https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/main/src/ReinforcementLearningZoo/src/algorithms/policy_gradient/td3.jl)

**Comment by VikasChidananda** [comment]
- [ ] Add a minimum working example
- [ ] Notebook
