### ISSUE TITLE
Editorial comments on JOSS submission

### ISSUE THREAD

**Issue by osorensen** [upb-lea/ElectricGrid.jl#112]
Whenever there are multiple references, please put them into the same set of parentheses using `[@key1;@key2]`, rather than citing each separately. This comment applies to lines 40-41, cf. screenshot below:

<img width="997" alt="image" src="https://github.com/upb-lea/ElectricGrid.jl/assets/21175639/6c4ec70d-9199-427b-ba27-4ae7e3a0aa08">

https://github.com/openjournals/joss-reviews/issues/5616

**Comment by Webbah** [comment]
Thank you for the hint.
I have changed the mutliple references and cross checked for others
