### ISSUE TITLE
Editorial comment on JOSS submission

### ISSUE THREAD

**Issue by osorensen** [upb-lea/ElectricGrid.jl#113]
The sentence highlighted below does not seem complete. What do you mean by "tools like (Lara et al., 2023)"?

<img width="998" alt="image" src="https://github.com/upb-lea/ElectricGrid.jl/assets/21175639/69215f5a-02b4-49bd-a440-833f62187706">

https://github.com/openjournals/joss-reviews/issues/5616

**Comment by osorensen** [comment]
If you mean "tools like the one presented in Lara et al. (2023)", then please rewrite to that. If you need it, note that you can create references without paranetheses with `@key`, i.e., dropping the square brackets.

**Comment by Webbah** [comment]
Yes, that was our intention and I am with you that the sentence is a bit "short". 
Thank you for the suggestions, changes have been updated
