### ISSUE TITLE
Editorial comments on JOSS submission

### ISSUE THREAD

**Issue by osorensen** [upb-lea/ElectricGrid.jl#114]
Please refer to the figures (e.g., "See Figure 2"), rather than stating "the figure below". This applies to both Figure 1 and Figure 2.

<img width="1002" alt="image" src="https://github.com/upb-lea/ElectricGrid.jl/assets/21175639/03bde1fc-9b73-43e4-93f5-843bee18765b">

<img width="1020" alt="image" src="https://github.com/upb-lea/ElectricGrid.jl/assets/21175639/51c8b2f6-4ebd-4541-97a2-a0766e558656">

https://github.com/openjournals/joss-reviews/issues/5616

**Comment by Webbah** [comment]
Thank you for the suggestion. Changes have been made accordingly
