### ISSUE TITLE
Status and need of example scripts

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/ElectricGrid.jl#129]
I feel that some / most of the scripts within examples/scripts folder are not in a good shape:

- introduction statements per script are missing, that is, an explanation of each script's content and motivation
- - [x] Septimus
- inline documentation is mostly very sparse and erratic 
- - [x] Septimus
- some commands are commented out without further context
- - [x] Septimus
- some outputs after execution are irritating (e.g., env_eampe.jl outputs something regarding RL settings although it was never configured for RL-based control)  

Considering that some of these scripts have been not touched for months and that there seem also content overlaps to the notebooks from the examples folder I would like to ask the core devs to critically go through the scripts and either delete those which them not having added value or improve those which should be kept for documentation / tutorial purpose

**Comment by Webbah** [comment]
All old scripts have been deleted, rest tidied up and documented. 
please comment if further need of adjustments or close if ok

**Comment by Webbah** [comment]
Fine regarding last editorial checks
