### ISSUE TITLE
WP 2 - Modeling of a variable DC-Link voltage 

### ISSUE THREAD

**Issue by MarvinMeyer** [upb-lea/ElectricGrid.jl#23]
This issue deals with the modeling of a variable DC-link voltage. 

1.  First example can be a PV system: 
Based on irradiation and temperature curves, a variable output voltage should be obtained from the physical equations, depending on the filter current.

The implementation in Matlab ([Source](https://de.mathworks.com/help/physmod/sps/powersys/ref/pvarray.html)), based on the paper ([Source](https://www.sciencedirect.com/science/article/pii/S2090997714000182)), serves as a reference for the model.

 In the first step, a single-phase implementation is to be created, which can later also be used for the three-phase case with the use of an inverter.

2. Battery:....
3. Windturbin....
4. ?

**Comment by Webbah** [comment]
### General implementation of v_dc as function, callable in the env.step:

First ideas/brainstroming/keep in mind...:

- Compareable to the featureize function we could write a function that is called depending on the topology of the source (PV, Batt, windturbine,...).
- The topology could be labeled in the parameter dict. 
   - By default labeled as "ideal" assuming infinite source -> constant v_dc
- Example "PV": parameters of the PV-plant given in the parameter dict and used when the function is applied in the env.step

**Comment by MarvinMeyer** [comment]
Current status:

- PV systems are ready, but still need to be tested
- Batteries are in progress

**Comment by MarvinMeyer** [comment]
- [ ] Model internal resistance for loss calculation

**Comment by MarvinMeyer** [comment]
Create a structure containing the individual DC link voltages. In addition, the calculation of the stresses should be delayed by one time step.

**Comment by MarvinMeyer** [comment]
Merged branch into develop.
