### ISSUE TITLE
Creating DARE Package

### ISSUE THREAD

**Issue by janstenner** [upb-lea/ElectricGrid.jl#25]
We need to convert our project into a julia package including a DARE module.

Creating the easy-to-use dare wrapper will also be part of this issue.

**Comment by Webbah** [comment]
![Image](https://user-images.githubusercontent.com/1822491/212070921-800d3511-99b1-49cd-8d07-4da0a68f8cb4.png)

**Comment by Webbah** [comment]
- [ ] automatizing indexing for RL
- [ ] feature function to wrapper

**Comment by janstenner** [comment]
This is done (see issue #43 )
