### ISSUE TITLE
Steady State Startup

### ISSUE THREAD

**Issue by SeptimusBoshoff** [upb-lea/ElectricGrid.jl#29]
This is only an idea, but not priority

Currently the package only supports a black start condition. That is, when any simulation is run, the network always starts with an initial condition where every capacitor voltage and inductor current is set to zero. Then every source starts ramping up at exactly the same point in time. This is impractical, because it requires instantaneous communication between sources that are spatially distributed. Moreover, the behaviour of the network has a long settling time before entering a steady state, which may hold no interest to the user. As can be seen from the image below, it takes roughly 1 second before the signals reach a steady state.

![image](https://user-images.githubusercontent.com/105304410/212285780-6e8e68d3-a82a-4d55-9e05-7db35ff81ecc.png)

The solution is to load the LTI system with initial conditions that correspond to steady state conditions. Some of this information is already partially available from the power flow solution. However the power flow solution only contains the steady state values of the cables, not the filters. 

What should be done:

- Calculate the initial conditions for the filter capacitors and inductors in the time domain (this includes capacitor currents)
- Calculate the filter capacitor magnitude and phase
- Calculate the source voltage magnitude and phase
- Create a Black Start / Steady State flag which then loads the calculated values into the environment (x0 and y0)
- Load the controllers with the correct internal conditions

**Comment by Webbah** [comment]
@SeptimusBoshoff, great idea. Is this done already or will be done in future?
If not, please document the status here and close
