### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Webbah** [upb-lea/ElectricGrid.jl#31]
## User Documentation 
- Introduction to what is Dare?
- Overview functionality
- Tutorials 
  -  Install
  - Examples
  - Videos?

## API Documentation
- All (?) functions to be documented with appropriate syntax

## Tool(s)
- https://documenter.juliadocs.org/stable/

**Comment by Webbah** [comment]
- variable names: snake_case (small+split by _)

- function names: PascalCase 

- file names: (do not change old functions now!) snake_case

**Comment by Webbah** [comment]
- [ ] keep github readme up to date

**Comment by Webbah** [comment]
- [ ] Name for the package
- [ ] Name for the env

**Comment by SeptimusBoshoff** [comment]
for every source file

- [ ] Classical Controllers
- [ ] nodeconstructor
- [ ] environment
- [ ] power system theory
- [ ] dare wrapper

**Comment by VikasChidananda** [comment]
Julia package naming guidelines: https://pkgdocs.julialang.org/v1/creating-packages/

**Comment by janstenner** [comment]
I did merge a first version of the documentation with the commit c33e333405fb8d7c1db8b8806348457364f11ba3

**Comment by Webbah** [comment]
User guide available - to be kept up to date with new features
