### ISSUE TITLE
Environment Enhancements

### ISSUE THREAD

**Issue by VikasChidananda** [upb-lea/ElectricGrid.jl#35]
Add noise to the observations:

- [ ]  White Gaussian noise: `y(t)+ n(t)`

- [ ] noise varying with the source signal: `y(t) + n(x(t), t)`

Could also be an idea to add in the harmonics for the sources (up to half the simulation frequency)

**Comment by Webbah** [comment]
Noise processes are now available, should be easy to add in and can be stored for future work
