### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by MarvinMeyer** [upb-lea/ElectricGrid.jl#4]
This issue covers the creation of examples for all functions of the package. The examples should be well documented and easy to follow.

TODO:
- Python Notebooks
- [x] NodeConstructor

- Python Files
- [x] NodeConstructor

**Comment by Webbah** [comment]
Use it in general for example or close?

**Comment by SeptimusBoshoff** [comment]
Classical Controllers - Jupyter Notebooks

- [ ] Swing mode + Static Load
- [ ] Droop mode + Static Load
- [ ] Droop mode + Controllable Load
- [ ] VSG mode + Static Load + Controllable Load

**Comment by Webbah** [comment]
- [ ] WebIO not detected-error.
How can we solve that? Even if the plots show up, reopening the notebook results in this error again

**Comment by Webbah** [comment]
@janstenner and @SeptimusBoshoff, are the mentiones notebooks in progress or is it a wont fix?
If the latter, please mention or close the issue
