### ISSUE TITLE
Real Time Performance Tests

### ISSUE THREAD

**Issue by janstenner** [upb-lea/ElectricGrid.jl#97]
We want to investigate what factors are affecting our performance in which amount and then try to make it faster!

- [ ] create performance benchmarks
- [ ] optimize DataHook
- [x] optimize Classical Controllers

**Comment by VikasChidananda** [comment]
Some specification on performance benchmarks:
- run the benchmarks on CPU and GPU
- Profiling to find bottleneck (if any)
- Metrics for comparison: timesteps / unit time,  updates / unit time 
- vary NN architecture linearly with increasing nodes(N)  [learnable parameters M = AN + b]

- [ ] Open loop simulation (without control)
- [ ] Closed loop simulation (with reinforcement learning / classical controls?)

**Comment by VikasChidananda** [comment]
Ideas for configuring `num_sources` and `num_loads`:
- [ ] `num_sources` = `num_loads`
- [ ] set of all (`num_source_i`, `num_loads_j`) such that `num_source_i` + `num_loads_j` = `num_nodes` 
- [ ] stochastically choose `num_source` such that 'num_source' > `num_loads` and `num_source` + `num_loads` = `num_nodes`

**Comment by VikasChidananda** [comment]
[Reproducibility pitfalls](https://juliaci.github.io/BenchmarkTools.jl/dev/linuxtips/)

**Comment by Webbah** [comment]
the controllers we went through together.
How about the rest?
